[package]
name = "vanity-address-sol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.4.14"
solana-client = "1.10.8"
owo-colors = "1"